### ISSUE TITLE
roadmap(ble): implement support for more peripherals

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#1004]
see https://en.wikipedia.org/wiki/Bluetooth_Low_Energy

**Comment by gen2thomas** [comment]
Milestones:
* [x] move drivers to drivers/ble
* [x] move sphero driver to drivers/serial
* [x] move sphero adaptor to adaptors/serialport (#371 )
* [ ] ~~try to make mavlink to use serialport~~
* [x] try to make megapi to use serialport (#1062 )
* [x] try to make neurosky to use serialport (#1061 )
* [x] improve test coverage (#1051 )
* [x] improve README
* [x] fix missing check of err return values in examples (#765 )
* [x] add example for serial-port with BLE (#987 )
* [ ] ~~add new drivers or one as example~~

**Comment by gen2thomas** [comment]
Simple drivers can be added by copy the battery driver and replace the short characteristic value (0x2A6F for Humidity). The developer should own the related device. So implementing arbitrary drivers is not useful at the moment, but can be done with less effort when needed. For further reading see https://www.bluetooth.com/specifications/assigned-numbers/

**Comment by gen2thomas** [comment]
Fixed with [v2.4.0](https://github.com/hybridgroup/gobot/releases/tag/v2.4.0)
