### ISSUE TITLE
raspi with gpio.servo not work (like expected)

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#1032]
I create this new issue to collect all various former issues related to gpio.ServoDriver().
The ServoWriter interface is used. For raspi, it should normally work also without [pi-blaster](https://github.com/sarfata/pi-blaster) for [PWM0, PWM1](https://www.raspberry-pi-geek.de/ausgaben/rpg/2020/04/grundlagen-der-pulsweitenmodulation/). But this seems to be not implemented, because always the `/dev/pi-blaster` will  be returned from the pwmPin() function. 

So it seems this parts should be solved (something like a roadmap):

* [x] introduce variadic function for gpio drivers, see #998 
* [x] introduce usage of normal PWM pin, without pi-blaster (with variadic functions)
* [x] endpoints/angle not work like expected (adjustable with variadic functions), see #692 
* [x] fix pi-blaster usage (or the description how it needs to be configured), see #703 , #753 

I'm going to close all the old referenced issues in favor of this one.

**Comment by gen2thomas** [comment]
fix released with [v2.3.0](https://github.com/hybridgroup/gobot/releases/tag/v2.3.0)
